[window]
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.92
startup_mode = "Maximized"
decorations = "None"

[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"
args= ["-l", "-c", 'tmux -u a || tmux -u']
